[package]
name = "schemix"
version = "0.1.0"
edition = "2024"

[dependencies]
nom = "8.0.0"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
anyhow = "1.0"
